# Generated by Django 3.1.4 on 2020-12-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20201208_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available_colors',
            new_name='available_colours',
        ),
    ]
