# Generated by Django 3.1.4 on 2020-12-07 18:14

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_discounted', models.BooleanField(default=False)),
                ('discounted_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('thumbnail', models.URLField(max_length=1000)),
                ('gallery', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), size=None)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=50, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('available_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('available_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
    ]
